export const SETTINGS_SECTION_IDS = {
  sync: 'settings-section-sync',
  workspaces: 'settings-section-workspaces',
  autogit: 'settings-section-autogit',
  appearance: 'settings-section-appearance',
  transparency: 'settings-section-transparency',
  widgets: 'settings-section-widgets',
  dictation: 'settings-section-dictation',
  miniApps: 'settings-section-mini-apps',
  buzz: 'settings-section-buzz',
  content: 'settings-section-content',
  ai: 'settings-section-ai',
  workflow: 'settings-section-workflow',
  privacy: 'settings-section-privacy',
} as const
